dubbo:
  application:
    name: service-search
  registry:
    address:  zookeeper://192.168.200.200:2181
  consumer:
    check: false
    #超时时间
    timeout: 5000
    #失败后重试次数
    retries: 0
  protocol:
    port: -1

spring:
  data:
    solr:
      host: http://192.168.200.200:8983/solr/mycollection
  rabbitmq:
    host: 192.168.200.200
    username: admin
    password: admin
    virtual-host: /admin
    port: 5672
