dubbo:
  application:
    name: server-messages
  registry:
    address: zookeeper://192.168.200.200:2181
  consumer:
    check: false
  protocol:
    port: -1

spring:
  rabbitmq:
    host: 192.168.200.200
    username: admin
    password: admin
    virtual-host: /admin
