server:
  port: 8082

spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.200.200
    username: admin
    password: admin
    virtual-host: /admin
    port: 5672
  redis:
    host: 192.168.200.200
    port: 6379

dubbo:
  application:
    name: myshop-sso
  registry:
    address: zookeeper://192.168.200.200:2181
  consumer:
    check: false
    #超时时间
    timeout: 5000
    #失败后重试次数
    retries: 0

