dubbo:
  application:
    name: goods
  registry:
    address: zookeeper://120.24.220.176:2181
  protocol:
    port: -1
  consumer:
    check: false

spring:
  datasource:
    url: jdbc:mysql:///shop1909?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:com/qf/dao/*.xml
