server:
  port: 8080
spring:
  thymeleaf:
    cache: false

dubbo:
  registry:
    address: zookeeper://192.168.200.200:2181
  application:
    name: back
  consumer:
    check: false
  protocol:
    port: -1

#配置fdfs
fdfs:
  pool:
    jmx-enabled: false
  thumb-image:
    height: 100
    width: 100
  tracker-list:
    - 192.168.200.200:22122